# Workflow intended to run CNI plugin static QA and tests on GitHub-hosted Windows runners.

name: CI

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  GO_VERSION: 1.23

permissions:
  contents: read

jobs:
  checks:
    name: Run Checks
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-2022"]

    steps:
      - name: Checkout Code
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
        with:
          ref: ${{ github.ref }}

      - name: Setup Go
        uses: actions/setup-go@7b8cf10d4e4a01d4992d18a89f4d7dc5a3e6d6f4 # v4.3.0
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Lint
        uses: golangci/golangci-lint-action@55c2c1448f86e01eaae002a5a3a9624417608d84 # v6.5.2
        with:
          version: v1.62.2
          skip-cache: true
          args: --timeout=8m

      - name: Install runhcs
        shell: bash
        run: |
          HCSSHIM_VER=$(sed -E -n "s|\t*github.com/Microsoft/hcsshim (.*)|\1|p" go.mod)
          git clone https://github.com/Microsoft/hcsshim -b "$HCSSHIM_VER" /tmp/hcsshim
          cd /tmp/hcsshim
          go install ./...

      - name: Enable ICMP V4
        shell: pwsh
        run: |
          netsh advFirewall Firewall add rule name="Enable ICMP Protocal" protocol=icmpv4:8,any dir=in action=allow

      - name: Log Runner Interfaces
        shell: pwsh
        run: Get-NetIPAddress

      - name: Test
        env:
          ImageToUse: mcr.microsoft.com/windows/nanoserver:ltsc2022
        run: |
          mingw32-make.exe test
